export { AuthProvider } from './providers/auth-provider'
export { useAuth } from './providers/auth-provider'
export { AuthContext, type AuthState } from './providers/auth-provider'
export { AccountModalProvider, AccountModalContext, useAccountModal } from './providers/account-modal-provider'
export { AccountAvatarTrigger } from './components/account-avatar-trigger/AccountAvatarTrigger'
export { QuickWalletSwitcher } from './components/quick-wallet-switcher'
export { AccountModal } from './components/account-modal/AccountModal'
export { OnboardingStepper } from './components/onboarding-stepper'
export { OnboardingFlowProvider } from './providers/onboarding-flow-provider'
export { OnboardingFlowContext } from './providers/onboarding-flow-provider'
export { useOnboardingFlow } from './hooks/use-onboarding-flow'
export type { OnboardingState } from './hooks/use-onboarding-flow'
export { useSelectedWallet } from './hooks/use-selected-wallet'
export type { SelectedWalletView } from './hooks/use-selected-wallet'
export { useRecipientSuggestions } from './hooks/use-recipient-suggestions'
export type {
  RecipientSuggestionsView,
  UseRecipientSuggestionsOptions,
} from './hooks/use-recipient-suggestions.types'
export type { User, PrivyId, Wallet, Me, OnboardingInput, AuthError, WalletSource, ChainSwitchOutcome } from './domain/types'
export { DisconnectedTablePlaceholder } from './components/disconnected-table-placeholder/DisconnectedTablePlaceholder'
export { ConnectWalletGateButton } from './components/connect-wallet-gate-button/ConnectWalletGateButton'
export { useIsWalletConnected } from './components/use-is-wallet-connected'
