export const tokens = {
  background: 'var(--background)',
  surface: 'var(--surface)',
  surfaceElevated: 'var(--surface-elevated)',
  border: 'var(--border)',
  borderStrong: 'var(--border-strong)',
  text: 'var(--text)',
  textSecondary: 'var(--textSecondary)',
  textMuted: 'var(--textMuted)',
  textMutedStrong: 'var(--textMutedStrong)',
  textOnAccent: 'var(--textOnAccent)',
  accent: 'var(--accent)',
  accentHover: 'var(--accent-hover)',
  accentSoft: 'var(--accent-soft)',
  // Casino two-accent system (PRD 0008 §5.1): teal = safety/primary, magenta =
  // commitment (never a non-committing action), bright cyan = active/glow.
  accentPrimary: 'var(--accent-primary)',
  accentPrimaryBright: 'var(--accent-primary-bright)',
  accentAction: 'var(--accent-action)',
  // Casino surface ladder + literal win/loss + text names.
  bgBase: 'var(--bg-base)',
  bgRail: 'var(--bg-rail)',
  bgSurface: 'var(--bg-surface)',
  bgElevated: 'var(--bg-elevated)',
  win: 'var(--win)',
  loss: 'var(--loss)',
  // Type faces.
  fontDisplay: 'var(--font-display)',
  fontBody: 'var(--font-body)',
  directionUp: 'var(--directionUp)',
  directionUpSoft: 'var(--directionUp-soft)',
  directionDown: 'var(--directionDown)',
  directionDownSoft: 'var(--directionDown-soft)',
  warning: 'var(--warning)',
  info: 'var(--info)',
  success: 'var(--success)',
  successSoft: 'var(--success-soft)',
  textOnSuccess: 'var(--text-on-success)',
  danger: 'var(--danger)',
  dangerSoft: 'var(--danger-soft)',
  textOnDanger: 'var(--text-on-danger)',
  warningSoft: 'var(--warning-soft)',
  infoSoft: 'var(--info-soft)',
  scrim: 'var(--scrim)',
} as const
